from pydantic import BaseModel, EmailStr
from typing import Optional, List
from .task_schemas import TaskOut


class UserBase(BaseModel):
  """Common fields shared across user payloads.

  Attributes:
    email (EmailStr): Email address used for authentication.
  """

  email: EmailStr


class UserCreate(UserBase):
  """Payload used when registering a new account.

  Attributes:
    password (str): Plain text password that will be hashed server side.
  """

  password: str


class UserOut(UserBase):
  """Representation of a user returned by the API.

  Attributes:
    id (int): Identifier managed by the database.
  """

  id: int

  class Config:
    """Enable conversion from ORM objects."""

    from_attributes = True


class Token(BaseModel):
  """Access token returned after a successful login.

  Attributes:
    access_token (str): Encoded JWT generated by the backend.
    token_type (str): Token type, typically bearer.
  """

  access_token: str
  token_type: str
